# Generated by Django 2.0.6 on 2019-05-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdrssInfo',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('recipient', models.CharField(blank=True, max_length=20, null=True)),
                ('adress', models.CharField(blank=True, max_length=80, null=True)),
                ('zip_code', models.BigIntegerField(blank=True, null=True)),
                ('tel', models.BigIntegerField(blank=True, db_column='TEL', null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'adrss_info',
            },
        ),
        migrations.CreateModel(
            name='BookClassT',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('pid', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'book_class_t',
            },
        ),
        migrations.CreateModel(
            name='BooksT',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('press', models.CharField(blank=True, max_length=30, null=True)),
                ('press_date', models.DateField(blank=True, null=True)),
                ('edition', models.BigIntegerField(blank=True, null=True)),
                ('printing_time', models.DateField(blank=True, null=True)),
                ('impression', models.BigIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=20, null=True)),
                ('words', models.BigIntegerField(blank=True, null=True)),
                ('pages', models.BigIntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=20, null=True)),
                ('paper', models.CharField(blank=True, max_length=20, null=True)),
                ('packing', models.CharField(blank=True, max_length=20, null=True)),
                ('dd_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('save', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'books_t',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('count_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('my_or', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('or_num', models.IntegerField(blank=True, null=True)),
                ('recipient', models.CharField(blank=True, max_length=30, null=True)),
                ('adress', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('pwd', models.CharField(blank=True, max_length=30, null=True)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'user',
            },
        ),
    ]
